version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Deft2306!
      - MYSQL_DB=eMenu
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB=root:Deft2306!@tcp(5432:5432)/eMenu?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
