version: '3.8'
services:
  mysql:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Deft2306!
      - MYSQL_DB=eMenu
    ports:
      - '3306:3306'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mysql
