DROP TABLE IF EXISTS dish_ingredient;

DROP TABLE IF EXISTS dish_origin;

DROP TABLE IF EXISTS dish_category;

DROP TABLE IF EXISTS dish;

DROP TABLE IF EXISTS ingredient;

DROP TABLE IF EXISTS origin;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS favourite;